import {colors} from '@src/styles';
import {ms, vs} from '@src/styles/scalingUtils';
import {Dimensions, StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    paddingTop: ms(-10),
    marginTop: ms(-10),
  },
  headerCenter: {
    fontFamily: 'Poppins-Bold',
    fontSize: ms(15),
    lineHeight: ms(22),
    color: colors.darkMain,
  },
  headerLeftTouch: {
    flex: ms(1),
    justifyContent: 'center',
  },
  wrapDuration: {
    marginTop: vs(20),
  },
  durationNumber: {
    fontFamily: 'Poppins-Medium',
    fontSize: ms(24),
    color: colors.darkMain,
    textAlign: 'center',
    lineHeight: ms(36),
  },
  durationText: {
    fontSize: ms(14),
    color: '#8F96A5',
    textAlign: 'center',
  },
  bottomRowContainer: {
    margin: ms(10),
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  titleImage: {
    width: ms(180),
    height: ms(15),
    position: 'absolute',
    top: ms(18),
  },
  title: {
    fontFamily: 'Poppins-Bold',
    fontSize: ms(20),
    lineHeight: ms(30),
    textAlign: 'center',
    color: colors.darkMain,
    zIndex: 1,
  },
  viewTitle: {flexDirection: 'column', alignItems: 'center'},
  subTitle: {textAlign: 'center', fontSize: ms(12), lineHeight: ms(18), color: '#3B404A'},
  viewCircleFirst: {
    marginTop: ms(20),
    borderRadius: 250,
    borderWidth: ms(1),
    borderColor: colors.grey,
    width: Dimensions.get('screen').width - ms(50),
    height: Dimensions.get('screen').width - ms(50),
    alignSelf: 'center',
  },
  viewCircleSecond: {
    // marginTop: ms(20),
    borderRadius: 250,
    // borderWidth: ms(1),
    borderColor: colors.silverTree,
    // width: Dimensions.get('screen').width - ms(90),
    // height: Dimensions.get('screen').width - ms(90),
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  AnimatedCircularProgress: {
    alignItems: 'center',
    marginTop: ms(20),
    justifyContent: 'flex-end',
  },
  viewTextFill: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
  },
  font40: {
    fontSize: ms(40),
  },
  fontBold: {
    fontFamily: 'Poppins-Bold',
    height: 'auto',
    textAlign: 'center',
    marginBottom: ms(20),
  },
  unitText: {
    color: '#485162',
    fontSize: ms(13),
    lineHeight: ms(20),
    fontFamily: 'Poppins-Regular',
    // marginBottom: ms(5),
  },
  goalText: {
    color: '#3B404A',
    fontSize: ms(28),
    // lineHeight: ms(30),
    fontFamily: 'Poppins-Light',
    // marginBottom: ms(5),
  },
  remainingText: {
    color: colors.manatee,
    fontSize: ms(12),
    lineHeight: ms(18),
    fontFamily: 'Poppins-Regular',
  },
  boxContent: {
    flexDirection: 'column',
    // alignItems: 'center',
    justifyContent: 'center',
    padding: ms(20),
    borderRadius: 16,
    backgroundColor: colors.white,
    shadowColor: colors.dark,
    shadowOffset: {
      width: ms(2),
      height: ms(4),
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    marginVertical: ms(-20),
  },
  titleField: {
    fontSize: ms(13),
    lineHeight: ms(20),
    textAlign: 'center',
    color: colors.manatee,
    marginBottom: 5,
  },
  fieldText: {
    fontSize: ms(15),
    lineHeight: ms(23),
    textAlign: 'center',
    color: colors.darkMain,
    fontWeight: 'bold',
  },
  btnViewDetails: {
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    backgroundColor: colors.white,
    shadowColor: colors.dark,
    shadowOffset: {
      width: ms(2),
      height: ms(4),
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    // position:'absolute', bottom: 0
  },
  line: {
    borderWidth: ms(2),
    width: ms(95),
    borderColor: colors.graySwitch,
    borderRadius: ms(36),
    marginBottom: vs(19),
    alignSelf: 'center',
    marginTop: ms(9),
  },
  modalDetails: {
    marginTop: 150,
    marginHorizontal: 0,
    marginBottom: 0,
    borderRadius: 0,
    backgroundColor: colors.white,
    borderTopLeftRadius: 13,
    borderTopRightRadius: 13,
  },
  bottomSheetTitle: {
    fontWeight: 'bold',
    fontSize: ms(15),
    textAlign: 'center',
    color: colors.darkMain,
  },
  bottomSheetText: {
    fontSize: ms(14),
    textAlign: 'center',
    color: colors.darkGray,
    alignSelf: 'center',
  },
  bottomSheetItem: {
    borderBottomColor: colors.gray,
    borderBottomWidth: 1,
    paddingVertical: ms(13),
    marginHorizontal: ms(30),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  itemLeft: {},
  itemLeftDate: {
    fontSize: ms(13),
    marginBottom: ms(10),
  },
  itemLeftnumber: {
    fontSize: ms(11),
  },
  itemRight: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  imgUp: {
    width: 15,
    height: 25,
  },
  itemRightNumber: {
    fontWeight: 'bold',
    fontSize: ms(15),
    color: colors.greenMain,
    marginLeft: 10,
  },
});

export default styles;
